import pygame

COLOR_TEXTO = (252, 1, 1)
COLOR_NEGRO = (0, 0, 0)
FONDO_JUEGO = (0,0)
VOLUMEN_JUEGO = 0.08
POSICION_X_MOSTRAR_TEXTO = 700
POSICION_VIDA_MUERTE_UNO=(670,570)
POSICION_VIDA_MUERTE_DOS=(670,640)
POSICION_VIDA_MUERTE_TRES=(670,710)
POSICION_JUGADOR = (300,750)
ANCHO = 800
ALTO = 800
TIEMPO_DISPARO_ENEMIGO = 500
TIEMPO_DISPARO_ENEMIGO_DOS = 500
TIEMPO_DISPARO_ENEMIGO_TRES = 250
ULTIMO_DISPARO_ENEMIGO = pygame.time.get_ticks()
ULTIMO_DISPARO_ENEMIGO_DOS = pygame.time.get_ticks()
ULTIMO_DISPARO_ENEMIGO_TRES = pygame.time.get_ticks()
BANDERA_COLISION = True
BANDERA_VIDA = True
puntuacion = 0
FPS = 30
MINUTOS = 1.60
RESTA_POR_SEGUNDO = 0.01
PRIMER_LUGAR = False